import express from 'express';
import * as commentController from '../controllers/commentController/index.js';
import * as middleWares from '../middleWares/index.js';
import { servErr } from './servErr.js';
const router=express.Router();
router.use(servErr);
router.post('/create',middleWares.authenticate,commentController.createCommentController);
router.put('/update',middleWares.authenticate,commentController.updateCommentController);
router.delete('/delete',middleWares.authenticate,commentController.deleteCommentController);
router.get('/userAllComment',middleWares.authenticate,commentController.getUserAllComment);
router.get('/postAllComment',middleWares.authenticate,commentController.getPostAllComment);
export default router;