import express from 'express';
const router=express.Router();
import * as middleWares from '../middleWares/index.js';
import * as taskController from '../controllers/taskController/index.js';
import { servErr } from './servErr.js';
router.use(servErr);
router.post('/create',middleWares.authenticate,taskController.createTaskController);
router.put('/update',middleWares.authenticate,taskController.updateTaskController);
router.delete('/delete',middleWares.authenticate,taskController.deleteTaskController);
router.get('/getUsersAll',middleWares.authenticate,taskController.getUsersAllTask);
router.get('/getAllTask',middleWares.authenticate,taskController.getAllTasks);
router.get('/getTask',middleWares.authenticate,taskController.getTaskController);
export default router;